name: Build, Push to AWS ECR, and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    name: Build Docker Image, Push to ECR, and Deploy to EKS

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image to ECR
        id: build-and-push
        run: |
          ECR_REGISTRY=153475762833.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/my-dagster-app-two:$IMAGE_TAG .
          docker push $ECR_REGISTRY/my-dagster-app-two:$IMAGE_TAG
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name dagster-poc --region us-east-1

      - name: Install Helm (if not already installed)
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Helm repository (if your chart is in a repository)
        run: helm repo add dagster https://dagster-io.github.io/helm

      - name: Update Helm repositories
        run: helm repo update

      - name: Deploy to EKS with Helm
        run: |
          helm upgrade dagster-dev dagster/dagster --namespace dev -f .helm/dev-values.yaml --set "dagster-user-deployments.deployments[0].image.tag=$IMAGE_TAG" --wait
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
